{
 "title": "E-Commerce Product Analytics",
 "tags": [
  "e-commerce",
  "products"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Most Popular Products (Added to Cart)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by(product_name) (product_cart_add_simple))",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "Total Website Visits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pageview_total_simple)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hourly Pageviews",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(pageview_total_counter[1h]))",
     "legendFormat": "Pageviews"
    }
   ]
  },
  {
   "title": "Products Added to Cart by Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(category_id) (product_cart_add_counter)",
     "legendFormat": "Category {{category_id}}"
    }
   ]
  }
 ]
}