{
 "title": "User Interaction Analytics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Events",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(event_total) or vector(0)" }
   ]
  },
  {
   "title": "Events by Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(category) (event_total)" }
   ]
  },
  {
   "title": "Hourly Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(event_total[$__interval])) or vector(0)",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "Popular products to add to the shopping cart",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, sum by(label) (event_total{category=\"Ecommerce\", action=\"add_to_cart\"}))"
    }
   ]
  }
 ]
}